### ISSUE TITLE
PCA plot issue?

### ISSUE THREAD

**Issue by mblue9** [stemangiola/rladiestunis2021_tidytranscriptomics#1]
Something may be up with the PCA plot here : https://stemangiola.github.io/rladiestunis2021_tidytranscriptomics/articles/tidytranscriptomics.html#exploratory-analyses-1
the samples don't separate like they used to e.g. see the PCA plot in the BiocEurope workshop in Dec:
https://stemangiola.github.io/bioceurope2020_tidytranscriptomics/articles/tidytranscriptomics.html

**Comment by mblue9** [comment]
We can just go with what we have a figure it out after.

**Comment by stemangiola** [comment]
> Something may be up with the PCA plot here : https://stemangiola.github.io/rladiestunis2021_tidytranscriptomics/articles/tidytranscriptomics.html#exploratory-analyses-1
> the samples don't separate like they used to e.g. see the PCA plot in the BiocEurope workshop in Dec:
> https://stemangiola.github.io/bioceurope2020_tidytranscriptomics/articles/tidytranscriptomics.html

Very annoying. Today I don't have time, but I will try to see. 
1) The first thing I would try is to see if applying PCA outside tidybulk we obtain old/new result. 
2) Then I would check if the input datasets from old/new workshops before PCA are the same

**Comment by mblue9** [comment]
> 1. The first thing I would try is to see if applying PCA outside tidybulk we obtain old/new result.
>2. Then I would check if the input datasets from old/new workshops before PCA are the same

1. I've just sent you an email with some code applying PCA outside tidybulk that shows it should be like we had it before, also pasted below. 
2. We're using the same dataset from the airway package as before so nothing's changed with that unless it's something tidySummarizedExperiment is doing

See what you think when you get a chance.

```
library(airway)
library(DESeq2)
library(edgeR)
library(ggplot2)
 
data(airway)
 
# PCA with edgeR
dgList <- SE2DGEList(airway)
group=dgList$samples$dex
keep.exprs <- filterByExpr(dgList, group=group)
dgList <- dgList[keep.exprs,, keep.lib.sizes=FALSE]
dgList <- calcNormFactors(dgList)
colnames(dgList$counts) <- substr(colnames(dgList$counts),start=8,stop=10)
colors <- rep(c("blue", "red"), 4)
plotMDS(dgList, col=colors[group], gene.selection="common")
 
# PCA with deseq2
dds_airway <- DESeqDataSet(airway,design= ~ cell + dex)
rld_airway <- rlogTransformation(dds_airway)
colnames(rld_airway) <- substr(colnames(rld_airway),start=8,stop=10)
pcaData <- plotPCA(rld_airway, intgroup=c("dex"), ntop = 500, returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
ggplot(pcaData, aes(PC1, PC2, color=dex)) +
  geom_point(size=3) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) +
  coord_fixed()
```

**Comment by stemangiola** [comment]
I am using Bioc 3_13 with R 4.1 plotMDS has changed (although I use prcomp so ths is unrelated)

> # PCA with edgeR
> dgList <- SE2DGEList(airway)
> group=dgList$samples$dex
> keep.exprs <- filterByExpr(dgList, group=group)
> dgList <- dgList[keep.exprs,, keep.lib.sizes=FALSE]
> dgList <- calcNormFactors(dgList)
> colnames(dgList$counts) <- substr(colnames(dgList$counts),start=8,stop=10)
> colors <- rep(c("blue", "red"), 4)
> plotMDS(dgList, col=colors[group], gene.selection="common")

![image](https://user-images.githubusercontent.com/7232890/114289660-211d5900-9abd-11eb-86ee-f1cb9f3d49c6.png)

With DESeq2 is as expected

> # PCA with deseq2
> dds_airway <- DESeqDataSet(airway,design= ~ cell + dex)
> rld_airway <- rlogTransformation(dds_airway)
> colnames(rld_airway) <- substr(colnames(rld_airway),start=8,stop=10)
> pcaData <- plotPCA(rld_airway, intgroup=c("dex"), ntop = 500, returnData=TRUE)
> percentVar <- round(100 * attr(pcaData, "percentVar"))
> ggplot(pcaData, aes(PC1, PC2, color=dex)) +
>   geom_point(size=3) +
>   xlab(paste0("PC1: ",percentVar[1],"% variance")) +
>   ylab(paste0("PC2: ",percentVar[2],"% variance")) +
>   coord_fixed()

![image](https://user-images.githubusercontent.com/7232890/114289723-6e99c600-9abd-11eb-99a6-9f80fd8b5bca.png)


DESeq2 with count_scaled

```r
dds_airway <- DESeqDataSet(counts_scaled,design= ~ cell + dex)
rld_airway <- rlogTransformation(dds_airway)
colnames(rld_airway) <- substr(colnames(rld_airway),start=8,stop=10)
pcaData <- plotPCA(rld_airway, intgroup=c("dex"), ntop = 500, returnData=TRUE)
percentVar <- round(100 * attr(pcaData, "percentVar"))
ggplot(pcaData, aes(PC1, PC2, color=dex)) +
    geom_point(size=3) +
    xlab(paste0("PC1: ",percentVar[1],"% variance")) +
    ylab(paste0("PC2: ",percentVar[2],"% variance")) +
    coord_fixed()
```

![image](https://user-images.githubusercontent.com/7232890/114289856-8a519c00-9abe-11eb-9e8a-b7d49ec2181f.png)


So the issue must be in tidybulk. However is strange, as I did not touch PCA for a while. I am investigating.

**Comment by mblue9** [comment]
I did a little investigating too and tidybulk produces the correct PCA plot on it's own i.e. the code we had before tidySummarizedExperiment. I tested tidybulk versions 1.3.1, 1.2.2, 1.2.1 and 1.2.0 with this and all produce the correct PCA.
```
library(airway) 
library(stringr)
library(ggplot2)
library(ggrepel)
library(tidybulk)
data(airway)
  airway %>%
  tidybulk() %>%
  mutate(sample_name = str_remove(sample, "SRR1039")) %>%
  mutate(symbol = AnnotationDbi::mapIds(org.Hs.eg.db::org.Hs.eg.db,
    keys = as.character(feature),
    keytype = "ENSEMBL",
    column = "SYMBOL",
    multiVals = "first"
  )) %>% 
  keep_abundant(factor_of_interest = dex) %>%
  scale_abundance() %>% 
  reduce_dimensions(method = "PCA") %>%
  pivot_sample() %>%
  ggplot(aes(x = PC1, y = PC2, colour = dex, shape = cell)) +
  geom_point() +
  geom_text_repel(aes(label = sample_name), show.legend = FALSE) 
```
![PCA_without_tidySE](https://user-images.githubusercontent.com/5591821/114300331-b3226300-9ab7-11eb-800f-fb097ac5e901.png)


But when you add in tidySummarizedExperiment with tidybulk 1.3.1 that's when the plot looks weird e.g using below

```
library(airway) 
library(stringr)
library(ggplot2)
library(ggrepel)
library(tidybulk)
library(tidySummarizedExperiment)
data(airway)
  airway %>%
  mutate(sample_name = str_remove(sample, "SRR1039")) %>%
  mutate(symbol = AnnotationDbi::mapIds(org.Hs.eg.db::org.Hs.eg.db,
    keys = transcript,
    keytype = "ENSEMBL",
    column = "SYMBOL",
    multiVals = "first"
  )) %>% 
      keep_abundant(factor_of_interest = dex) %>%
      scale_abundance() %>% 
      reduce_dimensions(method = "PCA") %>%
       pivot_sample() %>%
  ggplot(aes(x = PC1, y = PC2, colour = dex, shape = cell)) +
  geom_point() +
  geom_text_repel(aes(label = sample_name), show.legend = FALSE) 
```
![PCA_with_tidySE](https://user-images.githubusercontent.com/5591821/114300336-b87fad80-9ab7-11eb-822e-908723f085c7.png)

**Comment by stemangiola** [comment]
Hello @mblue9 I found out the scaling was missing. Now it's fixed. Thanks for your care!

https://github.com/stemangiola/tidybulk/commit/b4a6f2722ca634c4205c77daf7b20be64bfbd957

**Comment by mblue9** [comment]
Great! I've triggered a build to fix it in the material here then will close this.

**Comment by mblue9** [comment]
Build failed, with this error do I need to change transcript to feature?
```
Quitting from lines 165-177 (tidytranscriptomics.Rmd) 
Error: processing vignette 'tidytranscriptomics.Rmd' failed with diagnostics:
Problem with `mutate()` input `symbol`.
✖ object 'transcript' not found
ℹ Input `symbol` is `AnnotationDbi::mapIds(...)`.
--- failed re-building ‘tidytranscriptomics.Rmd’
```

**Comment by stemangiola** [comment]
> Build failed, with this error do I need to change transcript to feature?

I suspect so because I have update master and Bioconductor of tidySE.

Sorryyyyy

**Comment by mblue9** [comment]
That's no probs just wanted to check.

**Comment by mblue9** [comment]
Ah I need to wait for stemangiola/tidybulk@b4a6f27 to be pushed to master to fix the PCA plot. Can you ping me when that happens.

**Comment by mblue9** [comment]
@stemangiola I can rebuild the website here to fix the PCA plot now that the fix is merged but do we need a version bump on tidybulk master? 
At the moment master is 1.3.1 same as what we have in the website before the fix.

**Comment by stemangiola** [comment]
Done! For master.

Type: Package
Package: tidybulk
Title: Brings transcriptomics to the tidyverse 
Version: 1.3.2

**Comment by mblue9** [comment]
Great! Website is fixed now, so closing this.
